version: '3.1'

services:
  mongo:
    image: mongo:4.4.12
    container_name: mongo_api_twitter
    ports:
      - 27017:27017
    #volumes:
    # - db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: dio
      MONGO_INITDB_ROOT_PASSWORD: dio

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dio
      ME_CONFIG_MONGODB_ADMINPASSWORD: dio
      ME_CONFIG_MONGODB_URL: mongodb://dio:dio@mongo:27017/
#volumes:
#  db:
